### ISSUE TITLE
Clone symfony.sh with private repo?

### ISSUE THREAD

**Issue by koftikes** [aurimasniekis/flex-server#5]
Hello!
Thank you for yours project.

In documentation you discriped a way how to upload recipes to server 
`git clone git@github.com:symfony/recipes.git ./recipes`
I have a next questions:
1 . Did you have any ways how I can store recipes from https://github.com/symfony/recipes-contrib and https://github.com/symfony/recipes?
2. Auto updating  this recipes to my flex-server?
3. Adding my personal repo, symfony and symfony-contrib to my flex-server?

Thank you in advance.

**Comment by aurimasniekis** [comment]
Hi,

The library by the default wraps original symfony.sh server and just adds additional recipes. That clone was just an example to get some recipes.

**Comment by koftikes** [comment]
Thank you, for answer.
If you add this to documentation it's will be great )
