### ISSUE TITLE
Failures when CURL not installed

### ISSUE THREAD

**Issue by cyberemissary** [aurimasniekis/flex-server#6]
The machine where I setup the server happened to not have php-curl extension installed, so guzzle fell back on using `StreamHandler` which relies on **fopen** for reading data.

This caused the application to be extremely slow, and frequently fail completely with below error:

```
PHP Fatal error:  Uncaught RuntimeException: Error creating resource: [message] fopen(https://symfony.sh/p/symfony,intl,iv4.0.9,1522662761): failed to open stream: HTTP request failed! 
[file] /srv/flex-server/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php\n[line] 323 in /srv/flex-server/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php:252
Stack trace:
#0 /srv/flex-server/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(334): GuzzleHttp\\Handler\\StreamHandler->createResource(Object(Closure))
#1 /srv/flex-server/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(51): GuzzleHttp\\Handler\\StreamHandler->createStream(Object(GuzzleHttp\\Psr7\\ServerRequest), Array)
#2 /srv/flex-server/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(66): GuzzleHttp\\Handler\\StreamHandler->__invoke(Object(GuzzleHttp\\Psr7\\ServerRequest), Array)
#3 /srv/flex-server/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\ServerRequest),...'
```

Took me a while to figure out what's going on as it was working fine on my local system (which of course had the curl).

I recommend adding a note about CURL requirement to the README. Or maybe even add it to `composer.json` file so users can't even install the server without curl extension

**Comment by aurimasniekis** [comment]
It's problem with your php.ini configuration, You have to make sure it allows access foreign URL using fopen. Curl is not a hard requirement.
